name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 * * * *'  # Corre todo hora
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Fork
        uses: actions/checkout@v2

      - name: Set Up Git
        run: |
          git config user.name "Arthur"
          git config user.email "arthurpedreca@gmail.com"

      - name: Add Remote Upstream
        run: git remote add upstream https://github.com/norisjunior/fiapesp32

      - name: Fetch Upstream Changes
        run: git fetch upstream

      - name: Merge Upstream Changes
        run: |
          git checkout main  # Ou o nome da sua branch principal
          git merge upstream/main

      - name: Push Changes
        run: git push origin main  # Ou o nome da sua branch
